kind: pipeline
name: default

# clone:
#   depth: 50

steps:
- name: compose up
  image: docker/compose:1.24.0-rc1
  secrets: [DOCKER_SOCKET,DOMAIN,IP_RANGE,TIMEZONE,AIRFLOW_EMAIL,AIRFLOW_USER,AIRFLOW_FIRSTNAME,AIRFLOW_LASTNAME,AIRFLOW_PASSWORD,AIRFLOW_FERNET_KEY,AIRFLOW_DATABASE_NAME,AIRFLOW_DATABASE_USERNAME,AIRFLOW_DATABASE_PASSWORD,WAREHOUSE_NAME,WAREHOUSE_USERNAME,WAREHOUSE_PASSWORD,MINIO_ACCESS_KEY,MINIO_SECRET_KEY]
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker-compose down
    - docker volume rm airflowstack_airflow_data
    - docker volume rm airflowstack_airflow_worker_data
    - docker volume rm airflowstack_minio_data
    - docker volume rm airflowstack_redis_data
    - docker volume rm airflowstack_warehouse_data
    - docker-compose up -d

volumes:
- name: dockersock
  host:
    path: /volume1/docker/config/docker.sock


