version: "3"

networks:
  airflow:
    driver: bridge
    ipam:
      config:
        - subnet: ${IP_RANGE}.0/24
  web:
    external: true

services:
  airflow-database:
    container_name: airflow-database
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=${AIRFLOW_DATABASE_NAME}
      - POSTGRESQL_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
    volumes:
      - airflow_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      airflow:
        ipv4_address: ${IP_RANGE}.110

  warehouse:
    container_name: warehouse
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=${WAREHOUSE_NAME}
      - POSTGRESQL_USERNAME=${WAREHOUSE_USERNAME}
      - POSTGRESQL_PASSWORD=${WAREHOUSE_PASSWORD}
    volumes:
      - warehouse_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      airflow:
        ipv4_address: ${IP_RANGE}.120

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      - airflow

  airflow-worker:
    container_name: airflow-worker
    image: bitnami/airflow-worker:latest
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-database
    volumes:
      - airflow_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      - airflow

  airflow-scheduler:
    container_name: airflow-scheduler
    image: bitnami/airflow-scheduler:latest
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-database
      - AIRFLOW_LOAD_EXAMPLES=yes
    volumes:
      - airflow_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      - airflow

  airflow:
    container_name: airflow
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-database
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_FIRSTNAME=${AIRFLOW_FIRSTNAME}
      - AIRFLOW_LASTNAME=${AIRFLOW_LASTNAME}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=${TIMEZONE}
    labels:
      traefik.enable: "true"
      traefik.airflow.frontend.rule: "Host:airflow.${DOMAIN}"
      traefik.airflow.backend: "airflow-service"
      traefik.airflow.docker.network: "web"
      traefik.airflow.port: "8080"
      traefik.dagger.frontend.rule: "Host:dagger.${DOMAIN}"
      traefik.dagger.backend: "dagger-service"
      traefik.dagger.docker.network: "web"
      traefik.dagger.port: "2000"
    networks:
      - web
      - airflow
    ports:
      - '8080:8080'
      - '2000:2000'
    volumes:
      - airflow_data:/bitnami

  metabase:
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - "metabase_data:/data"
    environment:
      - MB_DB_FILE=/data/metabase.db
    image: metabase/metabase
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:metabase.${DOMAIN}"
      traefik.backend: "metabase-service"
      traefik.docker.network: "web"
      traefik.port: "3000"
    networks:
      - web
      - airflow

  minio:
    volumes:
    - minio_data:/data
    ports:
    - "9010:9000"
    environment:
    - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
    - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:minio.${DOMAIN}"
      traefik.backend: "minio-service"
      traefik.docker.network: "web"
      traefik.port: "9000"
    networks:
      web:
      airflow:
        ipv4_address: ${IP_RANGE}.130
    command: server /data
    container_name: minio
    image: minio/minio

volumes:
  airflow_data:
    driver: local
  airflow_worker_data:
    driver: local
  metabase_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  warehouse_data:
    driver: local