version: "3"

networks:
  airflow:
    driver: bridge
    ipam:
      config:
        - subnet: ${IP_RANGE}.0/24
  web:
    external: true

services:
  airflow-database:
    container_name: airflow-database
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=${AIRFLOW_DATABASE_NAME}
      - POSTGRESQL_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
    volumes:
      - airflow_database_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      airflow:
        ipv4_address: ${IP_RANGE}.110

  warehouse:
    container_name: warehouse
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=${WAREHOUSE_NAME}
      - POSTGRESQL_USERNAME=${WAREHOUSE_USERNAME}
      - POSTGRESQL_PASSWORD=${WAREHOUSE_PASSWORD}
    volumes:
      - warehouse_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      airflow:
        ipv4_address: ${IP_RANGE}.120

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      - airflow

  airflow-worker:
    container_name: airflow-worker
    image: bitnami/airflow-worker:latest
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-database
    volumes:
      - airflow_worker_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      - airflow

  airflow-scheduler:
    container_name: airflow-scheduler
    image: bitnami/airflow-scheduler:latest
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-database
      - AIRFLOW_LOAD_EXAMPLES=yes
    volumes:
      - airflow_scheduler_data:/bitnami
    labels:
      traefik.enable: "false"
    networks:
      - airflow

  airflow:
    container_name: airflow
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_DATABASE_HOST=airflow-database
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:airflow.${DOMAIN}"
      traefik.backend: "airflow-service"
      traefik.docker.network: "web"
      traefik.port: "8080"
    networks:
      - web
      - airflow
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami

  metabase:
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - "metabase_data:/data"
    environment:
      - MB_DB_FILE=/data/metabase.db
    image: metabase/metabase
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:metabase.${DOMAIN}"
      traefik.backend: "metabase-service"
      traefik.docker.network: "web"
      traefik.port: "3000"
    networks:
      - web
      - airflow

volumes:
  airflow_database_data:
    external: true
  airflow_data:
    external: true
  airflow_scheduler_data:
    external: true
  airflow_worker_data:
    external: true
  metabase_data:
    external: true
  redis_data:
    external: true
  warehouse_data:
    external: true